// src/components/models/contact/Computer.tsx
"use client";
import { useGLTF } from "@react-three/drei";

const Computer = (props: React.JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/computer-optimized-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes as any).Object_2?.geometry}
        material={materials.default}
      />
    </group>
  );
};

useGLTF.preload("/models/computer-optimized-transformed.glb");

export default Computer;

// src/lib/components/models/contact/Computer.svelte
<script lang="ts">
  import { T } from '@threlte/core';
  import { useDraco, useGltf } from '@threlte/extras';

  const gltf = useGltf('/models/computer-optimized-transformed.glb', { dracoLoader: useDraco() });
</script>

{#if $gltf?.nodes.Object_2}
  <T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_2.geometry}
      material={$gltf.materials.default}
    />
  </T.Group>
{/if}
