// src/lib/components/Button.svelte
<script lang="ts">
  let { text = '', className = '', id = '' }: { text?: string; className?: string; id?: string } = $props();

  function handleClick(e: Event) {
    e.preventDefault();
    if (!id) return;
    const target = document.getElementById('counter');
    if (target) {
      const offset = window.innerHeight * 0.15;
      const top = target.getBoundingClientRect().top + window.pageYOffset - offset;
      window.scrollTo({ top, behavior: 'smooth' });
    }
  }
</script>

<a onclick={handleClick} class="{className} cta-wrapper" href="#counter">
  <div class="cta-button group">
    <div class="bg-circle"></div>
    <p class="text">{text}</p>
    <div class="arrow-wrapper">
      <img src="/images/arrow-down.svg" alt="arrow" />
    </div>
  </div>
</a>

// src/components/Button.tsx
"use client";

interface ButtonProps {
  text: string;
  className?: string;
  id?: string;
}

const Button = ({ text, className, id }: ButtonProps) => (
  <a
    onClick={(e) => {
      e.preventDefault();
      const target = document.getElementById("counter");
      if (target && id) {
        const offset = window.innerHeight * 0.15;
        const top = target.getBoundingClientRect().top + window.pageYOffset - offset;
        window.scrollTo({ top, behavior: "smooth" });
      }
    }}
    className={`${className ?? ""} cta-wrapper`}
  >
    <div className="cta-button group">
      <div className="bg-circle" />
      <p className="text">{text}</p>
      <div className="arrow-wrapper">
        <img src="/images/arrow-down.svg" alt="arrow" />
      </div>
    </div>
  </a>
);

export default Button;
