// src/lib/sections/Experience.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import gsap from 'gsap';
  import { t, tRaw } from '$lib/i18n';
  import { ScrollTrigger } from 'gsap/ScrollTrigger';
  import { expCards } from '$lib/constants';
  import TitleHeader from '$components/TitleHeader.svelte';
  import GlowCard from '$components/GlowCard.svelte';

  gsap.registerPlugin(ScrollTrigger);

  type CardData = { review: string; title: string; date: string; responsibilities: string[] };

  const cards = $derived(
    ((tRaw('experience.cards') as CardData[]) ?? []).map((card, i) => ({
      ...expCards[i],
      ...card
    }))
  );

  onMount(() => {
    gsap.utils.toArray<HTMLElement>('.timeline-card').forEach((card) => {
      gsap.from(card, {
        xPercent: -100,
        opacity: 0,
        transformOrigin: 'left left',
        duration: 1,
        ease: 'power2.inOut',
        scrollTrigger: { trigger: card, start: 'top 80%' }
      });
    });

    gsap.to('.timeline', {
      transformOrigin: 'bottom bottom',
      ease: 'power1.inOut',
      scrollTrigger: {
        trigger: '.timeline',
        start: 'top center',
        end: '70% center',
        onUpdate: (self) => {
          gsap.to('.timeline', { scaleY: 1 - self.progress });
        }
      }
    });

    gsap.utils.toArray<HTMLElement>('.expText').forEach((text) => {
      gsap.from(text, {
        opacity: 0,
        xPercent: 0,
        duration: 1,
        ease: 'power2.inOut',
        scrollTrigger: { trigger: text, start: 'top 60%' }
      });
    });
  });
</script>

<section id="experience" class="flex-center md:mt-40 mt-20 section-padding xl:px-0">
  <div class="w-full h-full md:px-20 px-5">
    <TitleHeader title={t('experience.title')} sub={t('experience.sub')} />
    <div class="mt-32 relative">
      <div class="relative z-50 xl:space-y-32 space-y-10">
        {#each cards as card (card.title)}
          <div class="exp-card-wrapper">
            <div class="xl:w-2/6">
              <GlowCard {card}>
                <div>
                  <img src={card.imgPath} alt="exp-img" />
                </div>
              </GlowCard>
            </div>
            <div class="xl:w-4/6">
              <div class="flex items-start">
                <div class="timeline-wrapper">
                  <div class="timeline"></div>
                  <div class="gradient-line w-1 h-full"></div>
                </div>
                <div class="expText flex xl:gap-20 md:gap-10 gap-5 relative z-20">
                  <div class="timeline-logo">
                    <img src={card.logoPath} alt="logo" />
                  </div>
                  <div>
                    <h1 class="font-semibold text-3xl">{card.title}</h1>
                    <p class="my-5 text-white-50">🗓️&nbsp;{card.date}</p>
                    <p class="text-[#839CB5] italic">{t('experience.responsibilities')}</p>
                    <ul class="list-disc ms-5 mt-5 flex flex-col gap-5 text-white-50">
                      {#each card.responsibilities as responsibility, index}
                        <li class="text-lg">{responsibility}</li>
                      {/each}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {/each}
      </div>
    </div>
  </div>
</section>

// src/sections/Experience.tsx
"use client";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { useTranslations } from "next-intl";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { expCards } from "@/constants";
import TitleHeader from "@/components/TitleHeader";
import GlowCard from "@/components/GlowCard";

gsap.registerPlugin(ScrollTrigger);

const Experience = () => {
  const t = useTranslations("experience");
  type CardData = { review: string; title: string; date: string; responsibilities: string[] };
  const cards = (t.raw("cards") as CardData[]).map((card, i) => ({
    ...expCards[i],
    ...card,
  }));

  useGSAP(() => {
    gsap.utils.toArray<HTMLElement>(".timeline-card").forEach((card) => {
      gsap.from(card, {
        xPercent: -100,
        opacity: 0,
        transformOrigin: "left left",
        duration: 1,
        ease: "power2.inOut",
        scrollTrigger: { trigger: card, start: "top 80%" },
      });
    });

    gsap.to(".timeline", {
      transformOrigin: "bottom bottom",
      ease: "power1.inOut",
      scrollTrigger: {
        trigger: ".timeline",
        start: "top center",
        end: "70% center",
        onUpdate: (self) => {
          gsap.to(".timeline", { scaleY: 1 - self.progress });
        },
      },
    });

    gsap.utils.toArray<HTMLElement>(".expText").forEach((text) => {
      gsap.from(text, {
        opacity: 0,
        xPercent: 0,
        duration: 1,
        ease: "power2.inOut",
        scrollTrigger: { trigger: text, start: "top 60%" },
      });
    });
  }, []);

  return (
    <section id="experience" className="flex-center md:mt-40 mt-20 section-padding xl:px-0">
      <div className="w-full h-full md:px-20 px-5">
        <TitleHeader title={t("title")} sub={t("sub")} />
        <div className="mt-32 relative">
          <div className="relative z-50 xl:space-y-32 space-y-10">
            {cards.map((card) => (
              <div key={card.title} className="exp-card-wrapper">
                <div className="xl:w-2/6">
                  <GlowCard card={card}>
                    <div>
                      <img src={card.imgPath} alt="exp-img" />
                    </div>
                  </GlowCard>
                </div>
                <div className="xl:w-4/6">
                  <div className="flex items-start">
                    <div className="timeline-wrapper">
                      <div className="timeline" />
                      <div className="gradient-line w-1 h-full" />
                    </div>
                    <div className="expText flex xl:gap-20 md:gap-10 gap-5 relative z-20">
                      <div className="timeline-logo">
                        <img src={card.logoPath} alt="logo" />
                      </div>
                      <div>
                        <h1 className="font-semibold text-3xl">{card.title}</h1>
                        <p className="my-5 text-white-50">🗓️&nbsp;{card.date}</p>
                        <p className="text-[#839CB5] italic">{t("responsibilities")}</p>
                        <ul className="list-disc ms-5 mt-5 flex flex-col gap-5 text-white-50">
                          {card.responsibilities.map((responsibility, index) => (
                            <li key={index} className="text-lg">
                              {responsibility}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Experience;
